# Generated by Django 5.0.2 on 2024-04-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_dob_profile_date_of_birth_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
